name: Tests

on: [push, pull_request]

concurrency: ${{ github.ref }}

defaults:
  run:
    shell: bash

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.18', '1.17' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
